// Mocks generated by Mockito 5.4.6 from annotations
// in livria_user/test/features/book/infrastructure/repositories/exclusion_repository_impl_utest.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:livria_user/features/auth/infrastructure/datasource/auth_local_datasource.dart'
    as _i2;
import 'package:livria_user/features/book/infrastructure/datasource/exclusion_remote_datasource.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthLocalDataSource_0 extends _i1.SmartFake
    implements _i2.AuthLocalDataSource {
  _FakeAuthLocalDataSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExclusionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExclusionRemoteDataSource extends _i1.Mock
    implements _i3.ExclusionRemoteDataSource {
  MockExclusionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthLocalDataSource get authDs =>
      (super.noSuchMethod(
            Invocation.getter(#authDs),
            returnValue: _FakeAuthLocalDataSource_0(
              this,
              Invocation.getter(#authDs),
            ),
          )
          as _i2.AuthLocalDataSource);

  @override
  _i4.Future<void> postExclusion({
    required int? userId,
    required int? bookId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postExclusion, [], {
              #userId: userId,
              #bookId: bookId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteExclusion({
    required int? userId,
    required int? bookId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExclusion, [], {
              #userId: userId,
              #bookId: bookId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> getExclusionStatus({
    required int? userId,
    required int? bookId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExclusionStatus, [], {
              #userId: userId,
              #bookId: bookId,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<int>> getExclusionsList({required int? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getExclusionsList, [], {#userId: userId}),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);
}
