// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr-_NJasSKl1lTceuQ2QyJakEQ81kpQjc',
    appId: '1:303943428374:web:8b3cb7992518731bba8837',
    messagingSenderId: '303943428374',
    projectId: 'livriaadmindeploy',
    authDomain: 'livriaadmindeploy.firebaseapp.com',
    storageBucket: 'livriaadmindeploy.firebasestorage.app',
    measurementId: 'G-J8WP43HPXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUHBfl00Dmx3ozr4YW8yCfmFRwgBOv6MI',
    appId: '1:303943428374:android:485ae604f7ea7940ba8837',
    messagingSenderId: '303943428374',
    projectId: 'livriaadmindeploy',
    storageBucket: 'livriaadmindeploy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu_ikH6WRPKjrfgyQMaIjIdqNxslTXdiY',
    appId: '1:303943428374:ios:3e93ebedb3214f6cba8837',
    messagingSenderId: '303943428374',
    projectId: 'livriaadmindeploy',
    storageBucket: 'livriaadmindeploy.firebasestorage.app',
    iosBundleId: 'com.livria.livriaUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu_ikH6WRPKjrfgyQMaIjIdqNxslTXdiY',
    appId: '1:303943428374:ios:3e93ebedb3214f6cba8837',
    messagingSenderId: '303943428374',
    projectId: 'livriaadmindeploy',
    storageBucket: 'livriaadmindeploy.firebasestorage.app',
    iosBundleId: 'com.livria.livriaUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr-_NJasSKl1lTceuQ2QyJakEQ81kpQjc',
    appId: '1:303943428374:web:a4c3e4cc7f59baaaba8837',
    messagingSenderId: '303943428374',
    projectId: 'livriaadmindeploy',
    authDomain: 'livriaadmindeploy.firebaseapp.com',
    storageBucket: 'livriaadmindeploy.firebasestorage.app',
    measurementId: 'G-MXLFF3C81Y',
  );
}
